spring:
  application:
    name: oa
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/guns?useUnicode=true&useSSL=false&characterEncoding=UTF-8
      username: root
      password: hujing
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true  #开启二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启日志sql
